export const todoConstants = {
  SET_TODOS: "SET_TODOS",
  SET_TODOS_ERROR: "SET_TODOS",
  FETCH_TODOS: "FETCH_TODOS",
  FETCH_CREATE_TODO: "FETCH_CREATE_TODO",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_STATUS: "CHANGE_STATUS",
};
